name: qpotential
channels:
  - anaconda
  - omnia
  - ambermd
  - conda-forge
  - http://conda.binstar.org/omnia
  - defaults
dependencies:
  - python=3.6
  - pytraj=2.0.2
  - matplotlib=2.2
  - notebook=5
  - pandas=0.20
  - mdtraj=1.9.1
  - openmm=7.4.1
  - parmed=2.7.3
  - babel=2.4.0
  - scipy=0.19.1
  - packmol=1!18.013=0
