name: qpotential
channels:
  - anaconda
  - omnia
  - ambermd
  - conda-forge
  - http://conda.binstar.org/omnia
  - defaults
dependencies:
  - pytraj=2.0.2=py35_0
  - hdf5=1.8.17=2
  - netcdf4=1.2.4=np112py35_0
  - pytables=3.4.2=np112py35_0
  - alabaster=0.7.10=py35_1
  - asn1crypto=0.22.0=py35_0
  - babel=2.4.0=py35_0
  - backports=1.0=py35_1
  - backports.functools_lru_cache=1.5=py35_0
  - bleach=1.5.0=py35_0
  - bzip2=1.0.6=1
  - certifi=2017.4.17=py35_0
  - cffi=1.10.0=py35_0
  - chardet=3.0.2=py35_1
  - clangdev=6.0.0=default_0
  - cmake=3.10.2=4
  - conda=4.5.4=py35_0
  - conda-env=2.6.0=0
  - configurable-http-proxy=2.0.4=0
  - cryptography=1.9=py35_0
  - curl=7.52.1=0
  - cycler=0.10.0=py35_0
  - dbus=1.10.10=3
  - decorator=4.0.11=py35_0
  - docutils=0.14=py35_0
  - entrypoints=0.2.3=py35_1
  - expat=2.1.0=2
  - fastcache=1.0.2=py35_0
  - fontconfig=2.12.6=0
  - freetype=2.8.1=0
  - gettext=0.19.7=1
  - glib=2.51.4=0
  - gmp=6.1.2=0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=2
  - hdf4=4.2.12=0
  - html5lib=0.9999999=py35_0
  - icu=58.1=1
  - idna=2.5=py35_0
  - imagesize=0.7.1=py35_0
  - ipykernel=4.6.1=py35_0
  - ipython=6.1.0=py35_0
  - ipython_genutils=0.2.0=py35_0
  - ipywidgets=7.0.5=py35_0
  - jedi=0.10.0=py35_0
  - jinja2=2.9.5=py35_0
  - jpeg=9b=0
  - jsoncpp=0.10.6=1
  - jsonschema=2.5.1=py35_0
  - jupyter_client=5.1.0=py35_0
  - jupyter_core=4.3.0=py35_0
  - jupyterhub=0.7.2=py35_0
  - kiwisolver=1.0.1=py35_1
  - libarchive=3.2.1=2
  - libcxx=6.0.0=0
  - libffi=3.2.1=3
  - libiconv=1.15=0
  - libnetcdf=4.4.1=0
  - libpng=1.6.34=0
  - libsodium=1.0.10=0
  - libuv=1.11.0=0
  - libxcb=1.12=1
  - libxml2=2.9.4=4
  - llvm-meta=6.0.0=0
  - llvmdev=6.0.0=default_0
  - markupsafe=1.0=py35_0
  - matplotlib=2.2.0=py35_0
  - mistune=0.7.4=py35_0
  - mpmath=0.19=py35_2
  - nbconvert=5.2.1=py35_1
  - nbformat=4.3.0=py35_0
  - ncurses=5.9=10
  - nodejs=6.11.0=0
  - notebook=5.0.0=py35_0
  - numexpr=2.6.2=np112py35_0
  - numpydoc=0.7.0=py35_0
  - openmpi=2.1.2=0
  - pamela=0.3.0=py35_0
  - pandas=0.20.2=np112py35_1
  - pandoc=1.19.2=0
  - pandocfilters=1.4.1=py35_0
  - pcre=8.39=0
  - pexpect=4.2.1=py35_0
  - pickleshare=0.7.3=py35_0
  - prompt_toolkit=1.0.14=py35_0
  - ptyprocess=0.5.2=py35_0
  - pycosat=0.6.3=py35_0
  - pycparser=2.17=py35_0
  - pygments=2.2.0=py35_0
  - pyopenssl=16.2.0=py35_0
  - pyparsing=2.2.0=py35_0
  - pyqt=5.6.0=py35_4
  - pysocks=1.6.7=py35_0
  - python=3.5.5=0
  - python-dateutil=2.6.0=py35_0
  - pytz=2017.2=py35_0
  - pyzmq=16.0.2=py35_2
  - qt=5.6.2=7
  - readline=7.0=0
  - requests=2.18.1=py35_0
  - rhash=1.3.4=0
  - simplegeneric=0.8.1=py35_0
  - sip=4.18=py35_1
  - six=1.10.0=py35_1
  - snowballstemmer=1.2.1=py35_0
  - sphinx=1.6.3=py35_0
  - sphinxcontrib-websupport=1.0.1=py35_0
  - sqlalchemy=1.1.11=py35_0
  - sqlite=3.20.1=2
  - sympy=1.0=py35_0
  - terminado=0.6=py35_0
  - testpath=0.3=py35_0
  - tk=8.6.7=0
  - tornado=4.5.1=py35_0
  - traitlets=4.3.2=py35_0
  - typing=3.6.2=py35_0
  - urllib3=1.21.1=py35_1
  - wcwidth=0.1.7=py35_0
  - webencodings=0.5=py35_0
  - widgetsnbextension=3.0.3=py35_2
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - zeromq=4.2.1=1
  - zlib=1.2.11=0
  - libgcc=5.2.0=0
  - libgfortran=3.0.0=1
  - lzo=2.06=0
  - mkl=2017.0.3=0
  - numpy=1.12.1=py35_0
  - openssl=1.0.2j=0
  - pip=8.1.2=py35_0
  - pycrypto=2.6.1=py35_4
  - ruamel_yaml=0.11.14=py35_0
  - scipy=0.19.1=np112py35_0
  - setuptools=27.2.0=py35_0
  - system=5.8=2
  - wheel=0.29.0=py35_0
  - xz=5.2.2=0
  - yaml=0.1.6=0
  - ambermini=16.16.0=7
  - nglview=0.6.2.3=py35_0
  - openbabel=1!2.4.0=py35_2
  - openmoltools=0.8.1=py35_0
  - packmol=1!18.013=0
  - solvationtoolkit=0.4.3=py35_0
  - fftw3f=3.3.4=2
  - mdtraj=1.9.1=py35_0
  - openmm=7.1.1=py35_0
  - parmed=2.7.3=py35_1
  - pip:
    - amberlite==16.0
    - ambertools==17.0
    - mmpbsa.py==16.0
    - mpi4py==2.0.0
    - pdb4amber==1.3
    - pymsmt==16.0
    - sander==16.0
    - tables==3.4.2

